---
- name: Updating localtime
  command: /bin/cp /usr/share/zoneinfo/{{ system_timezone_location }} /etc/localtime
  tags: timezone

- name: Updating timezone
  template: src=default-timezone.j2 dest=/etc/timezone
  notify: Updating tzdata
  tags: timezone

